### ISSUE TITLE
add specific heat capacity

### ISSUE THREAD

**Issue by durack1** [durack1/CMIPOcean#4]
Current tables omit `cpocean`, needs to be added

@StephenGriffies

**Comment by durack1** [comment]
Just taking a look through [Griffies et al., 2016, GMD](https://gmd.copernicus.org/articles/9/3231/2016/gmd-9-3231-2016.pdf), `cpocean` appears to be the only scalar missing, we do request `rhozero`, I will amend tables to use the CMOR/Griffies et al names

In Griffies et al. 2016, we use the term "freezing point" which should replace the existing "freezing equation" in tables for consistency

Is there anything else that is omitted?

**Comment by StephenGriffies** [comment]
@durack1 I hope to dive into this asap, but might need another 24 hours to get myself out of other stuff.

**Comment by durack1** [comment]
@StephenGriffies sounds good, I've got a couple of other cleanups to do as well. Also better to get this right first than cleanup whilst attempting to collate info from the broader community
