### ISSUE TITLE
Reassign CMIP5 activity ids; Remove DCPP from tables; Correct institution id mappings

### ISSUE THREAD

**Issue by durack1** [durack1/CMIPOcean#6]
Updates required to [CMIP5](https://durack1.github.io/CMIPOcean/docs/CMIP5.html)

esmControl and esmHistorical to CMIP
esmrcp85 to ScenarioMIP
midHolocene, past1000 to PMIP
noVolcXXXX, volcInXXXX to ??

Remove all DCPP simulations from tables (will leave these in for now)

@taylor13 anything else that you've noticed?

**Comment by taylor13** [comment]
I’ve got a few things will send you soon.  This is taking a lot of time.

From: "Paul J. Durack" ***@***.***>
Reply-To: durack1/CMIPOcean ***@***.***>
Date: Thursday, May 13, 2021 at 3:10 PM
To: durack1/CMIPOcean ***@***.***>
Cc: "Taylor, Karl E." ***@***.***>, Mention ***@***.***>
Subject: [durack1/CMIPOcean] Reassign CMIP5 activity ids; Remove DCPP from tables (#6)


Updates required to CMIP5<https://urldefense.us/v3/__https:/durack1.github.io/CMIPOcean/docs/CMIP5.html__;!!G2kpM7uM-TzIFchu!mDI4Ko2bBswjzc246AxQiNpKymn5SMH7_RqJ8oIs5NJqW39FZ31VGCWWlojy1lk5GjA$>

esmControl and esmHistorical to CMIP
esmrcp85 to ScenarioMIP
midHolocene, past1000 to PMIP
noVolcXXXX, volcInXXXX to ??

Remove all DCPP simulations from tables

@taylor13<https://urldefense.us/v3/__https:/github.com/taylor13__;!!G2kpM7uM-TzIFchu!mDI4Ko2bBswjzc246AxQiNpKymn5SMH7_RqJ8oIs5NJqW39FZ31VGCWWlojyjyEKTR8$> anything else that you've noticed?

**Comment by durack1** [comment]
From @taylor13 

['BCC', 'BCCR']:
In CMIP3, BCCR was the Bjerknes Centre for Climate Research in Norway;  BCC did not contribute.
In CMIP5, BCC referred to the Beijing Climate Center, China Meteorological Administration,  BCC (CMA); BCCR did not contribute.
In CMIP6, BCC is the Beijing Climate Center;  NCC of Norway is a consortium that includes two institutions that are also affiliated with the Bjerknes Centre, so I think BCCR should map to NCC, not BCC. (NCC contributed to both CMIP5 and CMIP6, and BCCR contributed to CMIP3.) BCC has not changed from CMIP3 through CMIP6.

['IAP', 'CAS']:
In CMIP3, LASG-IAP contributed
In CMIP5, LASG-IAP and LASG-CESS contributed; they are
In CMIP6, CAS contributed; 
CAS hosts IAP (I think), and LASG is definitely under CAS, so I think LASG-IAP and LASG-CESS should map to CAS.  (Not sure where IAP appears?)

['INGV', 'ICHEC', 'CMCC']:
I can’t find ICHEC in CMIP3,5, or 6.  I don’t know if CMCC is a successor of INGV.

**Comment by durack1** [comment]
@taylor13 looks like `ICHEC` maps to `EC-Earth-Consortium` although they were likely a subset of that consortia in previous eras, see https://www.ichec.ie/news/irelands-contribution-cmip6-ec-earth-climate-simulations-published

**Comment by durack1** [comment]
I'm happy with the `INGV` mapping to `CMCC` see https://data.globalchange.gov/model/ingv-sxg

**Comment by durack1** [comment]
@taylor13 the changes noted above should now be live, if you have a chance, feel free to take a peek to validate, or spot any other issues
